---
- name: install mapr-client
  yum: name=mapr-client state=present
  become: yes
  become_user: root

- name: install hive
  yum: name={{item}} state=present
  become: yes
  become_user: root
  with_items:
    - mapr-hive-{{hive_version}}.{{hive_build}}
  when: hive_enabled

- name: install pig
  yum: name={{item}} state=present
  become: yes
  become_user: root
  with_items:
    - mapr-pig-{{pig_version}}.{{pig_build}}
  when: pig_enabled

- name: store the path to hive
  shell: rpm -ql mapr-hive  | head -2 | tail -1
  when: hive_enabled
  register: hive_home
  changed_when: false

- name: configure metastore
  become: yes
  become_user: root
  hadoop_properties:
    file: "{{hive_home.stdout}}/conf/hive-site.xml"
    name: "hive.metastore.uris" 
    value: "thrift://{{hostvars[hive_metastore_host].ansible_default_ipv4.address}}:9083" 
    state: present
  when: hive_enabled
