---
- name: install mapr-client
  yum: name=mapr-client state=present
  environment: proxy_env

- name: install hive and pig
  yum: name={{item}} state=present
  with_items:
    - mapr-hive
    - mapr-pig
  environment: proxy_env

- name: store the path to hive
  shell: rpm -ql mapr-hive  | head -2 | tail -1
  register: hive_home

- name: configure metastore
  hadoop_properties:
    file: "{{hive_home.stdout}}/conf/hive-site.xml"
    name: "hive.metastore.uris" 
    value: "thrift://{{hostvars[hive_metastore_host].ansible_default_ipv4.address}}:9083" 
    state: present